package FirstLesson11_7;


import java.awt.Color;
import java.awt.Toolkit;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rin's
 */
public class MyAlarm extends javax.swing.JFrame {

    /**
     * Creates new form MyAlarm
     */
    class TimeThread extends Thread {

        @Override
        public void run() {
            // query the system time after every second

            while (true) {
                try {
                    Calendar calendar = Calendar.getInstance();
                    int h = calendar.get(Calendar.HOUR_OF_DAY);
                    int m = calendar.get(Calendar.MINUTE);
                    int s = calendar.get(Calendar.SECOND);
                    String time = h + " : " + m + " : " + s;
                    txtFieldTimeNow.setText(time);
                    sleep(1000);
                    if (hh == h && mm == m && ss == s) {
                        if (t1 == null) {
                            AlarmThread at1 = new AlarmThread("Reng!!");
                            t1 = new Thread(at1);
                            t1.start();
                        }
                    }

                } catch (InterruptedException e) {
                    System.out.println(e);
                }
            }

        }

    }

    class AlarmThread implements Runnable {

        String mess;

        @Override
        public void run() {
            try {
                while (true) {
                    lbAlarm.setText(mess);
                    lbAlarm.setForeground(Color.BLACK);
                    Thread.sleep(200);
                    lbAlarm.setForeground(Color.RED);
                    Thread.sleep(200);
                    lbAlarm.setForeground(Color.WHITE);
                    Thread.sleep(200);
                }
            } catch (InterruptedException e) {
                System.out.println(e);
            }

        }

        public AlarmThread(String mess) {
            this.mess = mess;
        }

    }

    TimeThread tt = null;
    Thread t1 = null;
    Thread t2 = null;
    int hh = 0, mm = 0, ss = 0;

    public MyAlarm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTimeNow = new javax.swing.JLabel();
        txtFieldTimeNow = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        lbSetAlarm = new javax.swing.JLabel();
        txtHour = new javax.swing.JTextField();
        txtMinute = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        btnSetAlarm = new javax.swing.JButton();
        lbAlarm = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTimeNow.setText("Time now is");

        txtFieldTimeNow.setEditable(false);
        txtFieldTimeNow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFieldTimeNow.setForeground(new java.awt.Color(0, 0, 153));
        txtFieldTimeNow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldTimeNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTimeNowActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        lbSetAlarm.setText("Set Alarm");

        txtHour.setText("hh");

        txtMinute.setText("mm");

        txtSecond.setText("ss");

        btnSetAlarm.setText("Set");
        btnSetAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAlarmActionPerformed(evt);
            }
        });

        lbAlarm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSetAlarm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTimeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtFieldTimeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMinute, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnShow)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSetAlarm)))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lbAlarm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnStop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTimeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldTimeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSetAlarm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetAlarm))
                .addGap(86, 86, 86)
                .addComponent(lbAlarm)
                .addGap(31, 31, 31)
                .addComponent(btnStop)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldTimeNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTimeNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTimeNowActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // if tt has not yet init
        if (tt == null) {
            tt = new TimeThread();
            tt.start();
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSetAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetAlarmActionPerformed
        if (!txtHour.getText().equals("hh")
                && !txtMinute.getText().equals("mm")
                && !txtSecond.getText().equals("ss")) {
            hh = Integer.parseInt(txtHour.getText());
            mm = Integer.parseInt(txtMinute.getText());
            ss = Integer.parseInt(txtSecond.getText());
        }


    }//GEN-LAST:event_btnSetAlarmActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (t1 != null) {
            t1.interrupt();
            t1 = null;
        }
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MyAlarm ma = new MyAlarm();
        System.out.println(ma.txtHour.getText());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAlarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetAlarm;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lbAlarm;
    private javax.swing.JLabel lbSetAlarm;
    private javax.swing.JLabel lbTimeNow;
    private javax.swing.JTextField txtFieldTimeNow;
    private javax.swing.JTextField txtHour;
    private javax.swing.JTextField txtMinute;
    private javax.swing.JTextField txtSecond;
    // End of variables declaration//GEN-END:variables
}
