package NotePad;

import java.awt.event.KeyEvent;
import java.util.Arrays;

/**
 *
 * @author Rin's
 */
public class FindDialog extends javax.swing.JDialog {
    boolean isDown = true;
    String text = null;
    int [] a1 = null;
    int [] a = null;
    int index  = -1;
    int index1 = -1;
    Main md;
    
    /**
     * Creates new form FindDialog
     */
    public FindDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Find");
        setResizable(false);
        
        md = (Main)parent;
        setLocation(md.getX()+50, md.getY() +50);
        
        md.checker = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblFind = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rBtnUp = new javax.swing.JRadioButton();
        rBtnDown = new javax.swing.JRadioButton();
        ckbMatchcase = new javax.swing.JCheckBox();
        btnFind = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblFind.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblFind.setText("Find what:");

        txtFind.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        buttonGroup1.add(rBtnUp);
        rBtnUp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBtnUp.setText("Up");
        rBtnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnUpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnDown);
        rBtnDown.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBtnDown.setSelected(true);
        rBtnDown.setText("Down");
        rBtnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rBtnUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnDown)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnUp)
                    .addComponent(rBtnDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ckbMatchcase.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        ckbMatchcase.setText("Match case");
        ckbMatchcase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMatchcaseActionPerformed(evt);
            }
        });

        btnFind.setText("Find next");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbMatchcase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFind)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbMatchcase)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        md.checker = false;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    void findMCase() {
        if ( a!= null &&  a.length > 0) {
            try {
                if (isDown) {
                    index ++;
                    md.txtArea.setSelectionStart(a[index % a.length]);
                    md.txtArea.setSelectionEnd(a[index % a.length] + txtFind.getText().length());
                    if (index == a.length) {
                        index = 0;
                    }
                } else {
                    index--;
                    if (index < 0) {
                        index = a.length -1;
                    }
                    md.txtArea.setSelectionStart(a[index % a.length] - txtFind.getText().length() + 1);
                    md.txtArea.setSelectionEnd(a[index % a.length] + 1);
                }
            } catch (IndexOutOfBoundsException e) {
                System.out.println(e);
            }
        }
    }
    
    void find() {
        if ( a1!= null &&  a1.length > 0) {
            try {
                if (isDown) {
                    index1 ++;
                    md.txtArea.setSelectionStart(a1[index1 % a1.length]);
                    md.txtArea.setSelectionEnd(a1[index1 % a1.length] + txtFind.getText().length());
                    if (index1 == a1.length) {
                        index1 = 0;
                    }
                } else {
                    index1--;
                    if (index1 < 0) {
                        index1 = a1.length -1;
                    }
                    md.txtArea.setSelectionStart(a1[index1 % a1.length] - txtFind.getText().length() + 1);
                    md.txtArea.setSelectionEnd(a1[index1 % a1.length] + 1);
                }
            } catch (IndexOutOfBoundsException e) {
                System.out.println(e);
            }
        }
    }
    
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        if (ckbMatchcase.isSelected()) {
            findMCase();
        }else find();
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (ckbMatchcase.isSelected()) {
                findMCase();
            }else find();
        }
    }//GEN-LAST:event_txtFindKeyPressed

    boolean checkKeyCode(int code) {
        int ar[] = {8, 44, 45, 46, 47, 32, 61, 91,92,93,109,110,111,127,192};
        int arrCode[] = new int[27];
        int j = 0;
        for (int i = 96; i < 108; i++) {
            arrCode[j++] = i;
        }
        for (int i = 0; i < ar.length; i++) {
            if (code == ar[i]) {
                return true;
            }
        }
        for (int i = 0; i < arrCode.length; i++) {
            if (code == arrCode[i]) {
                return true;
            }
        }
        return false;
    }
    
    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        boolean c = checkKeyCode(code);
        if (md.checker &&  (((code >= 48 && code <= 57) || (code >= 65 && code <= 90)) || c == true)) {
            text = txtFind.getText();
            String source = md.txtArea.getText();
            if (!text.equals("")) {
                int[] arr = new int[source.length()];
                int[] arr1 = new int[source.length()];
                int ind = 0;
                int ind1 = 0;
                for (int i = 0; i <= source.length() - text.length(); i++) {
                    if (source.substring(i, i + text.length()).equals(text)) {
                        arr[ind++] = i;
                    }
                    if (source.substring(i, i + text.length()).equalsIgnoreCase(text)) {
                        arr1[ind1++] = i;
                    }
                }
                System.out.println("ind" + ind);
                System.out.println(Arrays.toString(arr));
                a = new int[ind];
                a1 = new int[ind1];
                for (int i = 0; i < ind; i++) {
                    a[i] = arr[i];
                }
                for (int i = 0; i < ind1; i++) {
                    a1[i] = arr1[i];
                }
            }
        }
    }//GEN-LAST:event_txtFindKeyReleased

    private void ckbMatchcaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMatchcaseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ckbMatchcaseActionPerformed

    private void rBtnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnUpActionPerformed
        // TODO add your handling code here:
        if (rBtnUp.isSelected()) {
            isDown = false;
        }
        
    }//GEN-LAST:event_rBtnUpActionPerformed

    private void rBtnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnDownActionPerformed
        // TODO add your handling code here:
        if (rBtnDown.isSelected()) {
            isDown = true;
        }
    }//GEN-LAST:event_rBtnDownActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        md.checker = false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FindDialog dialog = new FindDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckbMatchcase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFind;
    private javax.swing.JRadioButton rBtnDown;
    private javax.swing.JRadioButton rBtnUp;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
