/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicssample;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Rin's
 */
public class MyPaint extends javax.swing.JFrame {

    /**
     * Creates new form MyPaint
     */
    Point p1 = null, p2 = null;
    Graphics gPanel;
    Color c;
    public MyPaint() {
        initComponents();
        gPanel = jPanel1.getGraphics();
        c = Color.GREEN;
        btnColor.setForeground(c);
        jTextField1.setBackground(c);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
//        g.setFont(new Font("Arial", Font.BOLD, 40));
//        g.setColor(Color.GREEN);
//        g.drawString("Java is cool", 50, 100);
//        
//        //get graphics object
//        g = jPanel1.getGraphics();
//        g.setFont(new Font("Arial", Font.BOLD, 40));
//        g.setColor(Color.BLUE);
//        g.drawString("Java is cool", 70, 50);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckbFill = new javax.swing.JCheckBox();
        btnColor = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        ckbFill.setText("Fill color");

        btnColor.setText("Pick color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(ckbFill)
                .addGap(18, 18, 18)
                .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbFill)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        
//        if (ckbFill.isSelected()) {
//            if (SwingUtilities.isLeftMouseButton(evt)) {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                    gPanel.fillRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                }
//                p1 = p2 = null;
//            } else if (SwingUtilities.isRightMouseButton(evt)) {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                    gPanel.fillOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                }
//                p1 = p2 = null;
//            } else {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawLine(p1.x, p1.y, p2.x, p2.y);
//                }
//                p1 = p2 = null;
//            }
//        } else {
//            if (SwingUtilities.isLeftMouseButton(evt)) {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                }
//                p1 = p2 = null;
//            } else if (SwingUtilities.isRightMouseButton(evt)) {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
//                }
//                p1 = p2 = null;
//            } else {
//                p2 = evt.getPoint();
//                if (p1 != null && p2 != null) {
//                    gPanel.drawLine(p1.x, p1.y, p2.x, p2.y);
//                }
//                p1 = p2 = null;
//            }
//        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        p1 = evt.getPoint();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        c = JColorChooser.showDialog(null, "Select a color", c);
        if (c == null) {
            c = Color.GREEN;
        }
        btnColor.setForeground(c);
        jTextField1.setBackground(c);
        gPanel.setColor(c);
    }//GEN-LAST:event_btnColorActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        if (ckbFill.isSelected()) {
            if (SwingUtilities.isLeftMouseButton(evt)) {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                    gPanel.fillRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                }
                p1 = p2 = null;
            } else if (SwingUtilities.isRightMouseButton(evt)) {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                    gPanel.fillOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                }
                p1 = p2 = null;
            } else {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawLine(p1.x, p1.y, p2.x, p2.y);
                }
                p1 = p2 = null;
            }
        } else {
            if (SwingUtilities.isLeftMouseButton(evt)) {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawRect(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                }
                p1 = p2 = null;
            } else if (SwingUtilities.isRightMouseButton(evt)) {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawOval(p1.x, p1.y, Math.abs(p2.x-p1.x), Math.abs(p2.y-p1.y));
                }
                p1 = p2 = null;
            } else {
                p2 = evt.getPoint();
                if (p1 != null && p2 != null) {
                    gPanel.drawLine(p1.x, p1.y, p2.x, p2.y);
                }
                p1 = p2 = null;
            }
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JCheckBox ckbFill;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
