/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_18_7;

import com.entity.MyFont;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.FileReader;
import java.io.LineNumberReader;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author Rin's
 */
public class MenuDemo extends javax.swing.JFrame {

    String[] fontFamilies;
    String[] fontStyle = {"Plain", "Bold", "Italic", "Bold Italic"};

    /**
     * Creates new form MenuDemo
     */

//    private MyFont mf = null;
    public MenuDemo() {
        initComponents();
        loadFonts();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnColor = new javax.swing.JButton();
        cbbFont = new javax.swing.JComboBox<>();
        cbbStyle = new javax.swing.JComboBox<>();
        cbbSize = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniFont = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mnuWindow = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnColor.setIcon(new javax.swing.ImageIcon("E:\\Programing\\Java Swing\\Project\\SwingBasic\\icons\\color.png")); // NOI18N
        btnColor.setFocusable(false);
        btnColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnColor);

        cbbFont.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbFontItemStateChanged(evt);
            }
        });
        jToolBar1.add(cbbFont);

        cbbStyle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbStyleItemStateChanged(evt);
            }
        });
        jToolBar1.add(cbbStyle);

        cbbSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbSizeItemStateChanged(evt);
            }
        });
        jToolBar1.add(cbbSize);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        mnuFile.setText("File");

        mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniOpen.setIcon(new javax.swing.ImageIcon("E:\\Programing\\Java Swing\\Project\\SwingBasic\\icons\\open.png")); // NOI18N
        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mniOpen);

        mniFont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mniFont.setIcon(new javax.swing.ImageIcon("E:\\Programing\\Java Swing\\Project\\SwingBasic\\icons\\font.png")); // NOI18N
        mniFont.setText("Font");
        mniFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFontActionPerformed(evt);
            }
        });
        mnuFile.add(mniFont);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("E:\\Programing\\Java Swing\\Project\\SwingBasic\\icons\\edit.png")); // NOI18N
        jMenuItem1.setText("Edit");
        mnuFile.add(jMenuItem1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuView.setText("View");
        jMenuBar1.add(mnuView);

        mnuWindow.setText("Window");
        jMenuBar1.add(mnuWindow);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void loadFonts() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        fontFamilies = ge.getAvailableFontFamilyNames();
        for (String fontFamily : fontFamilies) {
            cbbFont.addItem(fontFamily);
        }
        for (String string : fontStyle) {
            cbbStyle.addItem(string);
        }
        for (int i = 8; i < 74; i += 2) {
            cbbSize.addItem(i + "");
        }
        cbbFont.setSelectedIndex(0);
        cbbStyle.setSelectedIndex(0);
        cbbSize.setSelectedIndex(0);

    }

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        // TODO add your handling code here:
        //open file dialog
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        if (fc.showOpenDialog(MenuDemo.this) == JFileChooser.APPROVE_OPTION) {
            //get selected file
            File f = fc.getSelectedFile();
            if (f != null && f.getName().endsWith("java")) {
                try {
                    LineNumberReader lnr = new LineNumberReader(new FileReader(f));
                    String line = "";
                    while ((line = lnr.readLine()) != null) {
                        txtArea.append(line + "\n");
                    }
                    lnr.close();
                } catch (Exception e) {
                    txtArea.setText(e + "");
                }
            }
        }
    }//GEN-LAST:event_mniOpenActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        Color c = Color.BLACK;
        c = JColorChooser.showDialog(null, "Select a color", Color.BLACK);
        if (c == null) {
            c = Color.BLACK;
        }
        txtArea.setForeground(c);

    }//GEN-LAST:event_btnColorActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void cbbFontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbFontItemStateChanged
        // TODO add your handling code here:
        txtArea.setFont(new Font(cbbFont.getSelectedItem().toString(), cbbStyle.getSelectedIndex(), (8 + 2 * cbbSize.getSelectedIndex())));
    }//GEN-LAST:event_cbbFontItemStateChanged

    private void cbbStyleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbStyleItemStateChanged
        // TODO add your handling code here:
        txtArea.setFont(new Font(cbbFont.getSelectedItem().toString(), cbbStyle.getSelectedIndex(), (8 + 2 * cbbSize.getSelectedIndex())));
    }//GEN-LAST:event_cbbStyleItemStateChanged

    private void cbbSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbSizeItemStateChanged
        // TODO add your handling code here:
        txtArea.setFont(new Font(cbbFont.getSelectedItem().toString(), cbbStyle.getSelectedIndex(), (8 + 2 * cbbSize.getSelectedIndex())));
    }//GEN-LAST:event_cbbSizeItemStateChanged

    private void mniFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFontActionPerformed
        // TODO add your handling code here:
        FontChooseDialog fcd = new FontChooseDialog(this, true);
        fcd.setVisible(true);
        MyFont mf1 = fcd.getMyFont();
        if (mf1 != null) {
//            txtArea.setFont(new Font(fontFamilies[mf1.getFont()], mf1.getStyle(), mf1.getSize()));
            cbbFont.setSelectedIndex(mf1.getFont());
            cbbStyle.setSelectedIndex(mf1.getStyle());
            cbbSize.setSelectedIndex(mf1.getSize());
        }
    }//GEN-LAST:event_mniFontActionPerformed

    public MyFont getFonts() {
        return new MyFont(cbbFont.getSelectedIndex(), cbbStyle.getSelectedIndex(), cbbSize.getSelectedIndex() * 2 + 8);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JComboBox<String> cbbFont;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cbbStyle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniFont;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuView;
    private javax.swing.JMenu mnuWindow;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
