/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i18nsample;

import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Rin's
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    //update GUI based on selected Locale
    public void updateGUI(Locale loc) {
        String base = "com.resources/MyDictionary";
        ResourceBundle rb = ResourceBundle.getBundle(base, loc);
        lblUsername.setText(rb.getString("username"));
        lblPass.setText(rb.getString("password"));
        lblCountry.setText(rb.getString("country"));
    }
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblCountry = new javax.swing.JLabel();
        cbbCountry = new javax.swing.JComboBox<>();
        rBtnEng = new javax.swing.JRadioButton();
        rBtnVN = new javax.swing.JRadioButton();
        rBtnEnglish = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblUsername.setText("Username");

        lblPass.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblPass.setText("Password");

        lblCountry.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCountry.setText("Country");

        cbbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VietNam", "China", "Japan", " " }));
        cbbCountry.setSelectedIndex(-1);
        cbbCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCountryItemStateChanged(evt);
            }
        });

        btnGroup.add(rBtnEng);
        rBtnEng.setText("Japanese");
        rBtnEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEngActionPerformed(evt);
            }
        });

        btnGroup.add(rBtnVN);
        rBtnVN.setText("Tiếng Việt");
        rBtnVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnVNActionPerformed(evt);
            }
        });

        btnGroup.add(rBtnEnglish);
        rBtnEnglish.setSelected(true);
        rBtnEnglish.setText("English");
        rBtnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEnglishActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPass)
                            .addComponent(lblCountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(txtPass))
                            .addComponent(cbbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rBtnEnglish)
                        .addGap(37, 37, 37)
                        .addComponent(rBtnEng)
                        .addGap(18, 18, 18)
                        .addComponent(rBtnVN)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(cbbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnEng)
                    .addComponent(rBtnVN)
                    .addComponent(rBtnEnglish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEngActionPerformed
        // TODO add your handling code here:
        // language code = ja, country code = JP
        Locale loc = new Locale("ja", "JP");
        updateGUI(loc);
    }//GEN-LAST:event_rBtnEngActionPerformed

    private void rBtnVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnVNActionPerformed
        // TODO add your handling code here:
        // language code = vi, country code = VN
        Locale loc = new Locale("vi", "VN");
        updateGUI(loc);
    }//GEN-LAST:event_rBtnVNActionPerformed

    private void rBtnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEnglishActionPerformed
        // TODO add your handling code here:
        // language code = en, country code = GB
        Locale loc = new Locale("en", "GB");
        updateGUI(loc);
    }//GEN-LAST:event_rBtnEnglishActionPerformed

    public void myFormat(Locale loc) {
        Date today = new Date();
        int price = 1560000;
        double number = 1.4;
        txtArea.setText("");
        NumberFormat nf = NumberFormat.getNumberInstance(loc);
        txtArea.setText("Formatting, locate = " + loc.getCountry());
        txtArea.append("\nNumber = " + nf.format(number));
        //currency
        nf = NumberFormat.getCurrencyInstance(loc);
        txtArea.append("\nMoney = " + nf.format(price));
        //date
        DateFormat df = DateFormat.getDateInstance(DateFormat.FULL, loc);
        txtArea.append("\nDate = " + df.format(today));
    }
    
    private void cbbCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCountryItemStateChanged
        // TODO add your handling code here:
        String country = cbbCountry.getSelectedItem().toString();
        if (country.equalsIgnoreCase("VietNam")) {
            myFormat(new Locale("vi","VN"));
        } else if (country.equalsIgnoreCase("Japan")) {
            myFormat(new Locale("ja", "JP"));
        } else {
            myFormat(new Locale("zh", "CN"));
        }
    }//GEN-LAST:event_cbbCountryItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JComboBox<String> cbbCountry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JRadioButton rBtnEng;
    private javax.swing.JRadioButton rBtnEnglish;
    private javax.swing.JRadioButton rBtnVN;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
